project:
  type: website
  output-dir: docs
  # Ensures Quarto includes all QMDs recursively
  resources:
    - code/**.qmd
    - figures/

website:
  title: "DSPG Workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: code/api_call.qmd
        text: API Call
      - href: code/rs_intro.qmd
        text: Remote Sensing

format:
  html:
    toc: true
    toc-location: left
    toc-collapse: true  
    code-fold: true
    theme: cosmo

