project:
  type: website
  output-dir: docs

website:
  title: "Remote Sensing Notes"
  navbar:
    left:
      - href: remote-sensing-intro.qmd

format:
  html:
    toc: true
    toc-location: left
    number-sections: true
    code-fold: true
    toc-depth: 3
    toc-title: "Contents"
    toc-collapse: true

